# Generated by Django 4.2.1 on 2023-05-25 12:14

from django.db import migrations, models
import django.db.models.deletion
import klass.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название урока')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Firstame')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('email', models.EmailField(help_text='ali@gmai', max_length=80, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, validators=[klass.utils.validate_phone_number], verbose_name='Phone number')),
                ('adress', models.CharField(max_length=50, verbose_name='Adress lived')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klass.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Firstame')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('email', models.EmailField(help_text='ali@gmai', max_length=80, verbose_name='Email')),
                ('phone', models.CharField(max_length=12, validators=[klass.utils.validate_phone_number], verbose_name='Phone number')),
                ('adress', models.CharField(max_length=50, verbose_name='Adress lived')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klass.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='klass.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
